package com.vhouzi.abc.admin.promote.mapper;

import com.vhouzi.abc.admin.promote.domain.PromoteCardAlloc;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromoteCardAllocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loyalty_card_th_allocation
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loyalty_card_th_allocation
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int insert(PromoteCardAlloc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loyalty_card_th_allocation
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    PromoteCardAlloc selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loyalty_card_th_allocation
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    List<PromoteCardAlloc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loyalty_card_th_allocation
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int updateByPrimaryKey(PromoteCardAlloc record);
}