package com.vhouzi.abc.admin.promote.mapper;

import com.vhouzi.abc.admin.promote.domain.PromoteInvite;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromoteInviteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tl_invite
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tl_invite
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int insert(PromoteInvite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tl_invite
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    PromoteInvite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tl_invite
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    List<PromoteInvite> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tl_invite
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int updateByPrimaryKey(PromoteInvite record);
}