package com.vhouzi.abc.admin.promote.mapper;

import com.vhouzi.abc.admin.promote.domain.PromoteLoyaltyCard;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromoteLoyaltyCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tm_loyalty_card
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tm_loyalty_card
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int insert(PromoteLoyaltyCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tm_loyalty_card
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    PromoteLoyaltyCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tm_loyalty_card
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    List<PromoteLoyaltyCard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tm_loyalty_card
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int updateByPrimaryKey(PromoteLoyaltyCard record);
}