package com.vhouzi.abc.admin.promote.mapper;

import com.vhouzi.abc.admin.promote.domain.PromoteLoyaltyCardDetail;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromoteLoyaltyCardDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tr_loyalty_card_detail
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tr_loyalty_card_detail
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int insert(PromoteLoyaltyCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tr_loyalty_card_detail
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    PromoteLoyaltyCardDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tr_loyalty_card_detail
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    List<PromoteLoyaltyCardDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote_tr_loyalty_card_detail
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    int updateByPrimaryKey(PromoteLoyaltyCardDetail record);
}