package com.vhouzi.abc.admin.promote.mapper;

import com.vhouzi.abc.admin.promote.domain.PromoteDistType;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromoteDistTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tm_type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tm_type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    int insert(PromoteDistType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tm_type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    PromoteDistType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tm_type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    List<PromoteDistType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tm_type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    int updateByPrimaryKey(PromoteDistType record);
}