package com.vhouzi.abc.admin.promote.mapper;

import com.vhouzi.abc.admin.promote.domain.PromoteDistStrategy;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PromoteDistStrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tr_strategy
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tr_strategy
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    int insert(PromoteDistStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tr_strategy
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    PromoteDistStrategy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tr_strategy
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    List<PromoteDistStrategy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_tr_strategy
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    int updateByPrimaryKey(PromoteDistStrategy record);
}