spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.server.address@
        register-enabled: false
        namespace: @nacos.config.namespace@
  profiles:
    active: @env@
logging:
  config: classpath:logback-spring.xml