package com.vhouzi.abc.admin.agent.mapper;

import com.vhouzi.abc.admin.agent.domain.AgentAccount;
import org.apache.ibatis.annotations.Mapper;
import java.util.List;

@Mapper
public interface AgentAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_member_account
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_member_account
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int insert(AgentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_member_account
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    AgentAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_member_account
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    List<AgentAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_member_account
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int updateByPrimaryKey(AgentAccount record);
}