package com.vhouzi.abc.admin.agent.mapper;

import com.vhouzi.abc.admin.agent.domain.AgentChannelExt;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AgentChannelExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_channel_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_channel_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int insert(AgentChannelExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_channel_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    AgentChannelExt selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_channel_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    List<AgentChannelExt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_channel_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int updateByPrimaryKey(AgentChannelExt record);
}