package com.vhouzi.abc.admin.agent.mapper;

import com.vhouzi.abc.admin.agent.domain.AgentRebate;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AgentRebateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_th_rebate
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_th_rebate
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int insert(AgentRebate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_th_rebate
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    AgentRebate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_th_rebate
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    List<AgentRebate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_th_rebate
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int updateByPrimaryKey(AgentRebate record);
}