package com.vhouzi.abc.admin.agent.mapper;

import com.vhouzi.abc.admin.agent.domain.AgentExt;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AgentExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_agent_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_agent_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int insert(AgentExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_agent_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    AgentExt selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_agent_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    List<AgentExt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_agent_ext
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int updateByPrimaryKey(AgentExt record);
}