package com.vhouzi.abc.admin.agent.mapper;

import com.vhouzi.abc.admin.agent.domain.AgentChannel;
import com.vhouzi.abc.admin.agent.dto.AgentChannelDTO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface AgentChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_channel
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int deleteByPrimaryKey(Long openMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_channel
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int insert(AgentChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_channel
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    AgentChannel selectByPrimaryKey(Long openMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_channel
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    List<AgentChannel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_channel
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int updateByPrimaryKey(AgentChannel record);

    AgentChannelDTO findSelective(Map<String, Object> params);
}