package com.vhouzi.abc.admin.agent.mapper;

import com.vhouzi.abc.admin.agent.domain.Agent;
import com.vhouzi.abc.admin.agent.dto.AgentDTO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface AgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_agent
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int deleteByPrimaryKey(Long openMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_agent
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int insert(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_agent
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    Agent selectByPrimaryKey(Long openMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_agent
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    List<Agent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_agent
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    int updateByPrimaryKey(Agent record);

    AgentDTO findSelective(Map<String, Object> params);
}