package com.vhouzi.abc.admin.promote.domain;

import java.util.Date;

public class PromoteMemberCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.no
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.name
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.cover
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.price
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.expires
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long expires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.ext1
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.ext2
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.status
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.create_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.create_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.extention
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String extention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tm_member_card.content
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.id
     *
     * @return the value of member_tm_member_card.id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.id
     *
     * @param id the value for member_tm_member_card.id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.no
     *
     * @return the value of member_tm_member_card.no
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.no
     *
     * @param no the value for member_tm_member_card.no
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.name
     *
     * @return the value of member_tm_member_card.name
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.name
     *
     * @param name the value for member_tm_member_card.name
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.type
     *
     * @return the value of member_tm_member_card.type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.type
     *
     * @param type the value for member_tm_member_card.type
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.cover
     *
     * @return the value of member_tm_member_card.cover
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.cover
     *
     * @param cover the value for member_tm_member_card.cover
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.price
     *
     * @return the value of member_tm_member_card.price
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.price
     *
     * @param price the value for member_tm_member_card.price
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.expires
     *
     * @return the value of member_tm_member_card.expires
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getExpires() {
        return expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.expires
     *
     * @param expires the value for member_tm_member_card.expires
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setExpires(Long expires) {
        this.expires = expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.ext1
     *
     * @return the value of member_tm_member_card.ext1
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.ext1
     *
     * @param ext1 the value for member_tm_member_card.ext1
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.ext2
     *
     * @return the value of member_tm_member_card.ext2
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.ext2
     *
     * @param ext2 the value for member_tm_member_card.ext2
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.status
     *
     * @return the value of member_tm_member_card.status
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.status
     *
     * @param status the value for member_tm_member_card.status
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.create_time
     *
     * @return the value of member_tm_member_card.create_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.create_time
     *
     * @param createTime the value for member_tm_member_card.create_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.create_user
     *
     * @return the value of member_tm_member_card.create_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.create_user
     *
     * @param createUser the value for member_tm_member_card.create_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.extention
     *
     * @return the value of member_tm_member_card.extention
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getExtention() {
        return extention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.extention
     *
     * @param extention the value for member_tm_member_card.extention
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setExtention(String extention) {
        this.extention = extention == null ? null : extention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tm_member_card.content
     *
     * @return the value of member_tm_member_card.content
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tm_member_card.content
     *
     * @param content the value for member_tm_member_card.content
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}