package com.vhouzi.abc.admin.promote.domain;

import java.util.Date;

public class PromoteInvite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitor_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long invitorMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitor_open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long invitorOpenMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitor_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String invitorRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitor_mobile
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String invitorMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitee_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long inviteeMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitee_open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long inviteeOpenMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitee_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String inviteeRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invitee_mobile
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String inviteeMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invite_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Date inviteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tl_invite.invite_source
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long inviteSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.id
     *
     * @return the value of member_tl_invite.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.id
     *
     * @param id the value for member_tl_invite.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitor_member_id
     *
     * @return the value of member_tl_invite.invitor_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getInvitorMemberId() {
        return invitorMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitor_member_id
     *
     * @param invitorMemberId the value for member_tl_invite.invitor_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInvitorMemberId(Long invitorMemberId) {
        this.invitorMemberId = invitorMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitor_open_member_id
     *
     * @return the value of member_tl_invite.invitor_open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getInvitorOpenMemberId() {
        return invitorOpenMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitor_open_member_id
     *
     * @param invitorOpenMemberId the value for member_tl_invite.invitor_open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInvitorOpenMemberId(Long invitorOpenMemberId) {
        this.invitorOpenMemberId = invitorOpenMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitor_realname
     *
     * @return the value of member_tl_invite.invitor_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getInvitorRealname() {
        return invitorRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitor_realname
     *
     * @param invitorRealname the value for member_tl_invite.invitor_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInvitorRealname(String invitorRealname) {
        this.invitorRealname = invitorRealname == null ? null : invitorRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitor_mobile
     *
     * @return the value of member_tl_invite.invitor_mobile
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getInvitorMobile() {
        return invitorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitor_mobile
     *
     * @param invitorMobile the value for member_tl_invite.invitor_mobile
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInvitorMobile(String invitorMobile) {
        this.invitorMobile = invitorMobile == null ? null : invitorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitee_member_id
     *
     * @return the value of member_tl_invite.invitee_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getInviteeMemberId() {
        return inviteeMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitee_member_id
     *
     * @param inviteeMemberId the value for member_tl_invite.invitee_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInviteeMemberId(Long inviteeMemberId) {
        this.inviteeMemberId = inviteeMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitee_open_member_id
     *
     * @return the value of member_tl_invite.invitee_open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getInviteeOpenMemberId() {
        return inviteeOpenMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitee_open_member_id
     *
     * @param inviteeOpenMemberId the value for member_tl_invite.invitee_open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInviteeOpenMemberId(Long inviteeOpenMemberId) {
        this.inviteeOpenMemberId = inviteeOpenMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitee_realname
     *
     * @return the value of member_tl_invite.invitee_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getInviteeRealname() {
        return inviteeRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitee_realname
     *
     * @param inviteeRealname the value for member_tl_invite.invitee_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInviteeRealname(String inviteeRealname) {
        this.inviteeRealname = inviteeRealname == null ? null : inviteeRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invitee_mobile
     *
     * @return the value of member_tl_invite.invitee_mobile
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getInviteeMobile() {
        return inviteeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invitee_mobile
     *
     * @param inviteeMobile the value for member_tl_invite.invitee_mobile
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInviteeMobile(String inviteeMobile) {
        this.inviteeMobile = inviteeMobile == null ? null : inviteeMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invite_time
     *
     * @return the value of member_tl_invite.invite_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Date getInviteTime() {
        return inviteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invite_time
     *
     * @param inviteTime the value for member_tl_invite.invite_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInviteTime(Date inviteTime) {
        this.inviteTime = inviteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tl_invite.invite_source
     *
     * @return the value of member_tl_invite.invite_source
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getInviteSource() {
        return inviteSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tl_invite.invite_source
     *
     * @param inviteSource the value for member_tl_invite.invite_source
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setInviteSource(Long inviteSource) {
        this.inviteSource = inviteSource;
    }
}