package com.vhouzi.abc.admin.promote.domain;

public class PromoteWeixinRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.member_id
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.open_member_id
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private Long openMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.openid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.nickname
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.sex
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.province
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.city
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.country
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.headimgurl
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.privilege
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String privilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.unionid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.subscribe_time
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private Long subscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.groupid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.tagid_list
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String tagidList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.subscribe_scene
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String subscribeScene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.qr_scene
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private Long qrScene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.qr_scene_str
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String qrSceneStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_weixin.mobile
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.member_id
     *
     * @return the value of member_tr_weixin.member_id
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.member_id
     *
     * @param memberId the value for member_tr_weixin.member_id
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.open_member_id
     *
     * @return the value of member_tr_weixin.open_member_id
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public Long getOpenMemberId() {
        return openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.open_member_id
     *
     * @param openMemberId the value for member_tr_weixin.open_member_id
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setOpenMemberId(Long openMemberId) {
        this.openMemberId = openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.openid
     *
     * @return the value of member_tr_weixin.openid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.openid
     *
     * @param openid the value for member_tr_weixin.openid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.nickname
     *
     * @return the value of member_tr_weixin.nickname
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.nickname
     *
     * @param nickname the value for member_tr_weixin.nickname
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.sex
     *
     * @return the value of member_tr_weixin.sex
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.sex
     *
     * @param sex the value for member_tr_weixin.sex
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.province
     *
     * @return the value of member_tr_weixin.province
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.province
     *
     * @param province the value for member_tr_weixin.province
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.city
     *
     * @return the value of member_tr_weixin.city
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.city
     *
     * @param city the value for member_tr_weixin.city
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.country
     *
     * @return the value of member_tr_weixin.country
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.country
     *
     * @param country the value for member_tr_weixin.country
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.headimgurl
     *
     * @return the value of member_tr_weixin.headimgurl
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.headimgurl
     *
     * @param headimgurl the value for member_tr_weixin.headimgurl
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.privilege
     *
     * @return the value of member_tr_weixin.privilege
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.privilege
     *
     * @param privilege the value for member_tr_weixin.privilege
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege == null ? null : privilege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.unionid
     *
     * @return the value of member_tr_weixin.unionid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.unionid
     *
     * @param unionid the value for member_tr_weixin.unionid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.subscribe_time
     *
     * @return the value of member_tr_weixin.subscribe_time
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public Long getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.subscribe_time
     *
     * @param subscribeTime the value for member_tr_weixin.subscribe_time
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setSubscribeTime(Long subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.groupid
     *
     * @return the value of member_tr_weixin.groupid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.groupid
     *
     * @param groupid the value for member_tr_weixin.groupid
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.tagid_list
     *
     * @return the value of member_tr_weixin.tagid_list
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getTagidList() {
        return tagidList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.tagid_list
     *
     * @param tagidList the value for member_tr_weixin.tagid_list
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setTagidList(String tagidList) {
        this.tagidList = tagidList == null ? null : tagidList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.subscribe_scene
     *
     * @return the value of member_tr_weixin.subscribe_scene
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getSubscribeScene() {
        return subscribeScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.subscribe_scene
     *
     * @param subscribeScene the value for member_tr_weixin.subscribe_scene
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setSubscribeScene(String subscribeScene) {
        this.subscribeScene = subscribeScene == null ? null : subscribeScene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.qr_scene
     *
     * @return the value of member_tr_weixin.qr_scene
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public Long getQrScene() {
        return qrScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.qr_scene
     *
     * @param qrScene the value for member_tr_weixin.qr_scene
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setQrScene(Long qrScene) {
        this.qrScene = qrScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.qr_scene_str
     *
     * @return the value of member_tr_weixin.qr_scene_str
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getQrSceneStr() {
        return qrSceneStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.qr_scene_str
     *
     * @param qrSceneStr the value for member_tr_weixin.qr_scene_str
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setQrSceneStr(String qrSceneStr) {
        this.qrSceneStr = qrSceneStr == null ? null : qrSceneStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_weixin.mobile
     *
     * @return the value of member_tr_weixin.mobile
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_weixin.mobile
     *
     * @param mobile the value for member_tr_weixin.mobile
     *
     * @mbggenerated Tue Jan 14 15:57:32 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }
}