package com.vhouzi.abc.admin.promote.domain;

import java.util.Date;

public class PromoteMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.unicode
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String unicode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long openMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.promote_type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long promoteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.content
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.create_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.expires
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long expires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.member_card_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long memberCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_promote_meta.extention
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String extention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.id
     *
     * @return the value of member_tr_promote_meta.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.id
     *
     * @param id the value for member_tr_promote_meta.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.unicode
     *
     * @return the value of member_tr_promote_meta.unicode
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getUnicode() {
        return unicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.unicode
     *
     * @param unicode the value for member_tr_promote_meta.unicode
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setUnicode(String unicode) {
        this.unicode = unicode == null ? null : unicode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.member_id
     *
     * @return the value of member_tr_promote_meta.member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.member_id
     *
     * @param memberId the value for member_tr_promote_meta.member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.open_member_id
     *
     * @return the value of member_tr_promote_meta.open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getOpenMemberId() {
        return openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.open_member_id
     *
     * @param openMemberId the value for member_tr_promote_meta.open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setOpenMemberId(Long openMemberId) {
        this.openMemberId = openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.promote_type
     *
     * @return the value of member_tr_promote_meta.promote_type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getPromoteType() {
        return promoteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.promote_type
     *
     * @param promoteType the value for member_tr_promote_meta.promote_type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setPromoteType(Long promoteType) {
        this.promoteType = promoteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.content
     *
     * @return the value of member_tr_promote_meta.content
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.content
     *
     * @param content the value for member_tr_promote_meta.content
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.create_time
     *
     * @return the value of member_tr_promote_meta.create_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.create_time
     *
     * @param createTime the value for member_tr_promote_meta.create_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.expires
     *
     * @return the value of member_tr_promote_meta.expires
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getExpires() {
        return expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.expires
     *
     * @param expires the value for member_tr_promote_meta.expires
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setExpires(Long expires) {
        this.expires = expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.member_card_id
     *
     * @return the value of member_tr_promote_meta.member_card_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getMemberCardId() {
        return memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.member_card_id
     *
     * @param memberCardId the value for member_tr_promote_meta.member_card_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setMemberCardId(Long memberCardId) {
        this.memberCardId = memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_promote_meta.extention
     *
     * @return the value of member_tr_promote_meta.extention
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getExtention() {
        return extention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_promote_meta.extention
     *
     * @param extention the value for member_tr_promote_meta.extention
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setExtention(String extention) {
        this.extention = extention == null ? null : extention.trim();
    }
}