package com.vhouzi.abc.admin.promote.domain;

import java.util.Date;

public class PromoteDistStrategy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.lower
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long lower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.upper
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long upper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.percentage
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String percentage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.quota
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String quota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.distibution_type_id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Long distibutionTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.create_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.update_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.create_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_tr_strategy.update_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.id
     *
     * @return the value of distribution_tr_strategy.id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.id
     *
     * @param id the value for distribution_tr_strategy.id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.lower
     *
     * @return the value of distribution_tr_strategy.lower
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getLower() {
        return lower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.lower
     *
     * @param lower the value for distribution_tr_strategy.lower
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setLower(Long lower) {
        this.lower = lower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.upper
     *
     * @return the value of distribution_tr_strategy.upper
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getUpper() {
        return upper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.upper
     *
     * @param upper the value for distribution_tr_strategy.upper
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setUpper(Long upper) {
        this.upper = upper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.percentage
     *
     * @return the value of distribution_tr_strategy.percentage
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.percentage
     *
     * @param percentage the value for distribution_tr_strategy.percentage
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setPercentage(String percentage) {
        this.percentage = percentage == null ? null : percentage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.quota
     *
     * @return the value of distribution_tr_strategy.quota
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getQuota() {
        return quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.quota
     *
     * @param quota the value for distribution_tr_strategy.quota
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setQuota(String quota) {
        this.quota = quota == null ? null : quota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.distibution_type_id
     *
     * @return the value of distribution_tr_strategy.distibution_type_id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Long getDistibutionTypeId() {
        return distibutionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.distibution_type_id
     *
     * @param distibutionTypeId the value for distribution_tr_strategy.distibution_type_id
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setDistibutionTypeId(Long distibutionTypeId) {
        this.distibutionTypeId = distibutionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.create_time
     *
     * @return the value of distribution_tr_strategy.create_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.create_time
     *
     * @param createTime the value for distribution_tr_strategy.create_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.update_time
     *
     * @return the value of distribution_tr_strategy.update_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.update_time
     *
     * @param updateTime the value for distribution_tr_strategy.update_time
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.create_user
     *
     * @return the value of distribution_tr_strategy.create_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.create_user
     *
     * @param createUser the value for distribution_tr_strategy.create_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_tr_strategy.update_user
     *
     * @return the value of distribution_tr_strategy.update_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_tr_strategy.update_user
     *
     * @param updateUser the value for distribution_tr_strategy.update_user
     *
     * @mbggenerated Wed Jan 08 11:16:48 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}