package com.vhouzi.abc.admin.promote.domain;

import java.util.Date;

public class PromoteLoyaltyCardDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String lotNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.redemption
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String redemption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.status
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.redeemer_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long redeemerMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.redeemer_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String redeemerRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tr_loyalty_card_detail.redemption_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Date redemptionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.id
     *
     * @return the value of promote_tr_loyalty_card_detail.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.id
     *
     * @param id the value for promote_tr_loyalty_card_detail.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.no
     *
     * @return the value of promote_tr_loyalty_card_detail.no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.no
     *
     * @param no the value for promote_tr_loyalty_card_detail.no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.lot_no
     *
     * @return the value of promote_tr_loyalty_card_detail.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getLotNo() {
        return lotNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.lot_no
     *
     * @param lotNo the value for promote_tr_loyalty_card_detail.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo == null ? null : lotNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.redemption
     *
     * @return the value of promote_tr_loyalty_card_detail.redemption
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getRedemption() {
        return redemption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.redemption
     *
     * @param redemption the value for promote_tr_loyalty_card_detail.redemption
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setRedemption(String redemption) {
        this.redemption = redemption == null ? null : redemption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.status
     *
     * @return the value of promote_tr_loyalty_card_detail.status
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.status
     *
     * @param status the value for promote_tr_loyalty_card_detail.status
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.redeemer_member_id
     *
     * @return the value of promote_tr_loyalty_card_detail.redeemer_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getRedeemerMemberId() {
        return redeemerMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.redeemer_member_id
     *
     * @param redeemerMemberId the value for promote_tr_loyalty_card_detail.redeemer_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setRedeemerMemberId(Long redeemerMemberId) {
        this.redeemerMemberId = redeemerMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.redeemer_realname
     *
     * @return the value of promote_tr_loyalty_card_detail.redeemer_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getRedeemerRealname() {
        return redeemerRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.redeemer_realname
     *
     * @param redeemerRealname the value for promote_tr_loyalty_card_detail.redeemer_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setRedeemerRealname(String redeemerRealname) {
        this.redeemerRealname = redeemerRealname == null ? null : redeemerRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tr_loyalty_card_detail.redemption_time
     *
     * @return the value of promote_tr_loyalty_card_detail.redemption_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Date getRedemptionTime() {
        return redemptionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tr_loyalty_card_detail.redemption_time
     *
     * @param redemptionTime the value for promote_tr_loyalty_card_detail.redemption_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setRedemptionTime(Date redemptionTime) {
        this.redemptionTime = redemptionTime;
    }
}