package com.vhouzi.abc.admin.promote.domain;

import java.util.Date;

public class PromoteCardAlloc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long openMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.member_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String memberRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String lotNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.total_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.used_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long usedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.allocate_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Date allocateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loyalty_card_th_allocation.allocate_user
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String allocateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.id
     *
     * @return the value of loyalty_card_th_allocation.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.id
     *
     * @param id the value for loyalty_card_th_allocation.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.member_id
     *
     * @return the value of loyalty_card_th_allocation.member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.member_id
     *
     * @param memberId the value for loyalty_card_th_allocation.member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.open_member_id
     *
     * @return the value of loyalty_card_th_allocation.open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getOpenMemberId() {
        return openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.open_member_id
     *
     * @param openMemberId the value for loyalty_card_th_allocation.open_member_id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setOpenMemberId(Long openMemberId) {
        this.openMemberId = openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.member_realname
     *
     * @return the value of loyalty_card_th_allocation.member_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getMemberRealname() {
        return memberRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.member_realname
     *
     * @param memberRealname the value for loyalty_card_th_allocation.member_realname
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setMemberRealname(String memberRealname) {
        this.memberRealname = memberRealname == null ? null : memberRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.lot_no
     *
     * @return the value of loyalty_card_th_allocation.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getLotNo() {
        return lotNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.lot_no
     *
     * @param lotNo the value for loyalty_card_th_allocation.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo == null ? null : lotNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.type
     *
     * @return the value of loyalty_card_th_allocation.type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.type
     *
     * @param type the value for loyalty_card_th_allocation.type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.total_num
     *
     * @return the value of loyalty_card_th_allocation.total_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.total_num
     *
     * @param totalNum the value for loyalty_card_th_allocation.total_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setTotalNum(Long totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.used_num
     *
     * @return the value of loyalty_card_th_allocation.used_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getUsedNum() {
        return usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.used_num
     *
     * @param usedNum the value for loyalty_card_th_allocation.used_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setUsedNum(Long usedNum) {
        this.usedNum = usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.allocate_time
     *
     * @return the value of loyalty_card_th_allocation.allocate_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Date getAllocateTime() {
        return allocateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.allocate_time
     *
     * @param allocateTime the value for loyalty_card_th_allocation.allocate_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setAllocateTime(Date allocateTime) {
        this.allocateTime = allocateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loyalty_card_th_allocation.allocate_user
     *
     * @return the value of loyalty_card_th_allocation.allocate_user
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getAllocateUser() {
        return allocateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loyalty_card_th_allocation.allocate_user
     *
     * @param allocateUser the value for loyalty_card_th_allocation.allocate_user
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setAllocateUser(String allocateUser) {
        this.allocateUser = allocateUser == null ? null : allocateUser.trim();
    }
}