package com.vhouzi.abc.admin.promote.domain;

import java.util.Date;

public class PromoteLoyaltyCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String lotNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.total_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.unit_price
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.status
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.create_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote_tm_loyalty_card.create_user
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.id
     *
     * @return the value of promote_tm_loyalty_card.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.id
     *
     * @param id the value for promote_tm_loyalty_card.id
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.lot_no
     *
     * @return the value of promote_tm_loyalty_card.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getLotNo() {
        return lotNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.lot_no
     *
     * @param lotNo the value for promote_tm_loyalty_card.lot_no
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo == null ? null : lotNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.type
     *
     * @return the value of promote_tm_loyalty_card.type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.type
     *
     * @param type the value for promote_tm_loyalty_card.type
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.total_num
     *
     * @return the value of promote_tm_loyalty_card.total_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.total_num
     *
     * @param totalNum the value for promote_tm_loyalty_card.total_num
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setTotalNum(Long totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.unit_price
     *
     * @return the value of promote_tm_loyalty_card.unit_price
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.unit_price
     *
     * @param unitPrice the value for promote_tm_loyalty_card.unit_price
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice == null ? null : unitPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.status
     *
     * @return the value of promote_tm_loyalty_card.status
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.status
     *
     * @param status the value for promote_tm_loyalty_card.status
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.create_time
     *
     * @return the value of promote_tm_loyalty_card.create_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.create_time
     *
     * @param createTime the value for promote_tm_loyalty_card.create_time
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote_tm_loyalty_card.create_user
     *
     * @return the value of promote_tm_loyalty_card.create_user
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote_tm_loyalty_card.create_user
     *
     * @param createUser the value for promote_tm_loyalty_card.create_user
     *
     * @mbggenerated Wed Jan 01 00:19:51 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }
}