package com.vhouzi.abc.admin.agent.domain;

import java.util.Date;

public class AgentBankAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.bank_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.bank_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.bank_branch
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String bankBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.bank_account_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String bankAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.bank_account_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String bankAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.card_attribute
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long cardAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.card_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.is_verified
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long isVerified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_bank_account.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String extention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.id
     *
     * @return the value of member_tr_bank_account.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.id
     *
     * @param id the value for member_tr_bank_account.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.member_id
     *
     * @return the value of member_tr_bank_account.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.member_id
     *
     * @param memberId the value for member_tr_bank_account.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.bank_id
     *
     * @return the value of member_tr_bank_account.bank_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.bank_id
     *
     * @param bankId the value for member_tr_bank_account.bank_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.bank_name
     *
     * @return the value of member_tr_bank_account.bank_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.bank_name
     *
     * @param bankName the value for member_tr_bank_account.bank_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.bank_branch
     *
     * @return the value of member_tr_bank_account.bank_branch
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.bank_branch
     *
     * @param bankBranch the value for member_tr_bank_account.bank_branch
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch == null ? null : bankBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.bank_account_no
     *
     * @return the value of member_tr_bank_account.bank_account_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getBankAccountNo() {
        return bankAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.bank_account_no
     *
     * @param bankAccountNo the value for member_tr_bank_account.bank_account_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo == null ? null : bankAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.bank_account_name
     *
     * @return the value of member_tr_bank_account.bank_account_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.bank_account_name
     *
     * @param bankAccountName the value for member_tr_bank_account.bank_account_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName == null ? null : bankAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.card_attribute
     *
     * @return the value of member_tr_bank_account.card_attribute
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getCardAttribute() {
        return cardAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.card_attribute
     *
     * @param cardAttribute the value for member_tr_bank_account.card_attribute
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCardAttribute(Long cardAttribute) {
        this.cardAttribute = cardAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.card_type
     *
     * @return the value of member_tr_bank_account.card_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.card_type
     *
     * @param cardType the value for member_tr_bank_account.card_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCardType(Long cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.province
     *
     * @return the value of member_tr_bank_account.province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.province
     *
     * @param province the value for member_tr_bank_account.province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.city
     *
     * @return the value of member_tr_bank_account.city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.city
     *
     * @param city the value for member_tr_bank_account.city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.is_verified
     *
     * @return the value of member_tr_bank_account.is_verified
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.is_verified
     *
     * @param isVerified the value for member_tr_bank_account.is_verified
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setIsVerified(Long isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.status
     *
     * @return the value of member_tr_bank_account.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.status
     *
     * @param status the value for member_tr_bank_account.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.create_time
     *
     * @return the value of member_tr_bank_account.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.create_time
     *
     * @param createTime the value for member_tr_bank_account.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.update_time
     *
     * @return the value of member_tr_bank_account.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.update_time
     *
     * @param updateTime the value for member_tr_bank_account.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.create_user
     *
     * @return the value of member_tr_bank_account.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.create_user
     *
     * @param createUser the value for member_tr_bank_account.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.update_user
     *
     * @return the value of member_tr_bank_account.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.update_user
     *
     * @param updateUser the value for member_tr_bank_account.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_bank_account.extention
     *
     * @return the value of member_tr_bank_account.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getExtention() {
        return extention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_bank_account.extention
     *
     * @param extention the value for member_tr_bank_account.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setExtention(String extention) {
        this.extention = extention == null ? null : extention.trim();
    }
}