package com.vhouzi.abc.admin.agent.domain;

public class AgentChannelExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.agent_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long agentMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.agent_real_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String agentRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.cert_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.cert_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.area
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.address
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.channel_source
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long channelSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.channel_source_extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String channelSourceExtention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_channel_ext.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String extention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.member_id
     *
     * @return the value of member_tr_channel_ext.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.member_id
     *
     * @param memberId the value for member_tr_channel_ext.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.agent_member_id
     *
     * @return the value of member_tr_channel_ext.agent_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getAgentMemberId() {
        return agentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.agent_member_id
     *
     * @param agentMemberId the value for member_tr_channel_ext.agent_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setAgentMemberId(Long agentMemberId) {
        this.agentMemberId = agentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.agent_real_name
     *
     * @return the value of member_tr_channel_ext.agent_real_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getAgentRealName() {
        return agentRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.agent_real_name
     *
     * @param agentRealName the value for member_tr_channel_ext.agent_real_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setAgentRealName(String agentRealName) {
        this.agentRealName = agentRealName == null ? null : agentRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.cert_type
     *
     * @return the value of member_tr_channel_ext.cert_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.cert_type
     *
     * @param certType the value for member_tr_channel_ext.cert_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCertType(Long certType) {
        this.certType = certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.cert_no
     *
     * @return the value of member_tr_channel_ext.cert_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.cert_no
     *
     * @param certNo the value for member_tr_channel_ext.cert_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.province
     *
     * @return the value of member_tr_channel_ext.province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.province
     *
     * @param province the value for member_tr_channel_ext.province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.city
     *
     * @return the value of member_tr_channel_ext.city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.city
     *
     * @param city the value for member_tr_channel_ext.city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.area
     *
     * @return the value of member_tr_channel_ext.area
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.area
     *
     * @param area the value for member_tr_channel_ext.area
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.address
     *
     * @return the value of member_tr_channel_ext.address
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.address
     *
     * @param address the value for member_tr_channel_ext.address
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.channel_source
     *
     * @return the value of member_tr_channel_ext.channel_source
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getChannelSource() {
        return channelSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.channel_source
     *
     * @param channelSource the value for member_tr_channel_ext.channel_source
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setChannelSource(Long channelSource) {
        this.channelSource = channelSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.channel_source_extention
     *
     * @return the value of member_tr_channel_ext.channel_source_extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getChannelSourceExtention() {
        return channelSourceExtention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.channel_source_extention
     *
     * @param channelSourceExtention the value for member_tr_channel_ext.channel_source_extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setChannelSourceExtention(String channelSourceExtention) {
        this.channelSourceExtention = channelSourceExtention == null ? null : channelSourceExtention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_channel_ext.extention
     *
     * @return the value of member_tr_channel_ext.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getExtention() {
        return extention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_channel_ext.extention
     *
     * @param extention the value for member_tr_channel_ext.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setExtention(String extention) {
        this.extention = extention == null ? null : extention.trim();
    }
}