package com.vhouzi.abc.admin.agent.domain;

import java.util.Date;

public class AgentExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.cert_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.cert_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date contractCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_effective_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date contractEffectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_invalid_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date contractInvalidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_end_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date contractEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_province_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_city_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_area_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_area
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String contractArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.contract_status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long contractStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.distribution_type_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long distributionTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.dedicated_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String dedicatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_agent_ext.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String extention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.member_id
     *
     * @return the value of member_tr_agent_ext.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.member_id
     *
     * @param memberId the value for member_tr_agent_ext.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.cert_type
     *
     * @return the value of member_tr_agent_ext.cert_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.cert_type
     *
     * @param certType the value for member_tr_agent_ext.cert_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCertType(Long certType) {
        this.certType = certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.cert_no
     *
     * @return the value of member_tr_agent_ext.cert_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.cert_no
     *
     * @param certNo the value for member_tr_agent_ext.cert_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_no
     *
     * @return the value of member_tr_agent_ext.contract_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_no
     *
     * @param contractNo the value for member_tr_agent_ext.contract_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_type
     *
     * @return the value of member_tr_agent_ext.contract_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_type
     *
     * @param contractType the value for member_tr_agent_ext.contract_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractType(Long contractType) {
        this.contractType = contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_amount
     *
     * @return the value of member_tr_agent_ext.contract_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_amount
     *
     * @param contractAmount the value for member_tr_agent_ext.contract_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractAmount(String contractAmount) {
        this.contractAmount = contractAmount == null ? null : contractAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_create_time
     *
     * @return the value of member_tr_agent_ext.contract_create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getContractCreateTime() {
        return contractCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_create_time
     *
     * @param contractCreateTime the value for member_tr_agent_ext.contract_create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractCreateTime(Date contractCreateTime) {
        this.contractCreateTime = contractCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_effective_time
     *
     * @return the value of member_tr_agent_ext.contract_effective_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getContractEffectiveTime() {
        return contractEffectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_effective_time
     *
     * @param contractEffectiveTime the value for member_tr_agent_ext.contract_effective_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractEffectiveTime(Date contractEffectiveTime) {
        this.contractEffectiveTime = contractEffectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_invalid_time
     *
     * @return the value of member_tr_agent_ext.contract_invalid_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getContractInvalidTime() {
        return contractInvalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_invalid_time
     *
     * @param contractInvalidTime the value for member_tr_agent_ext.contract_invalid_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractInvalidTime(Date contractInvalidTime) {
        this.contractInvalidTime = contractInvalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_end_time
     *
     * @return the value of member_tr_agent_ext.contract_end_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getContractEndTime() {
        return contractEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_end_time
     *
     * @param contractEndTime the value for member_tr_agent_ext.contract_end_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractEndTime(Date contractEndTime) {
        this.contractEndTime = contractEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_province_code
     *
     * @return the value of member_tr_agent_ext.contract_province_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractProvinceCode() {
        return contractProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_province_code
     *
     * @param contractProvinceCode the value for member_tr_agent_ext.contract_province_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractProvinceCode(String contractProvinceCode) {
        this.contractProvinceCode = contractProvinceCode == null ? null : contractProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_province
     *
     * @return the value of member_tr_agent_ext.contract_province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractProvince() {
        return contractProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_province
     *
     * @param contractProvince the value for member_tr_agent_ext.contract_province
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractProvince(String contractProvince) {
        this.contractProvince = contractProvince == null ? null : contractProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_city_code
     *
     * @return the value of member_tr_agent_ext.contract_city_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractCityCode() {
        return contractCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_city_code
     *
     * @param contractCityCode the value for member_tr_agent_ext.contract_city_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractCityCode(String contractCityCode) {
        this.contractCityCode = contractCityCode == null ? null : contractCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_city
     *
     * @return the value of member_tr_agent_ext.contract_city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractCity() {
        return contractCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_city
     *
     * @param contractCity the value for member_tr_agent_ext.contract_city
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractCity(String contractCity) {
        this.contractCity = contractCity == null ? null : contractCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_area_code
     *
     * @return the value of member_tr_agent_ext.contract_area_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractAreaCode() {
        return contractAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_area_code
     *
     * @param contractAreaCode the value for member_tr_agent_ext.contract_area_code
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractAreaCode(String contractAreaCode) {
        this.contractAreaCode = contractAreaCode == null ? null : contractAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_area
     *
     * @return the value of member_tr_agent_ext.contract_area
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getContractArea() {
        return contractArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_area
     *
     * @param contractArea the value for member_tr_agent_ext.contract_area
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractArea(String contractArea) {
        this.contractArea = contractArea == null ? null : contractArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.contract_status
     *
     * @return the value of member_tr_agent_ext.contract_status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getContractStatus() {
        return contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.contract_status
     *
     * @param contractStatus the value for member_tr_agent_ext.contract_status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setContractStatus(Long contractStatus) {
        this.contractStatus = contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.distribution_type_id
     *
     * @return the value of member_tr_agent_ext.distribution_type_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getDistributionTypeId() {
        return distributionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.distribution_type_id
     *
     * @param distributionTypeId the value for member_tr_agent_ext.distribution_type_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setDistributionTypeId(Long distributionTypeId) {
        this.distributionTypeId = distributionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.dedicated_user
     *
     * @return the value of member_tr_agent_ext.dedicated_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getDedicatedUser() {
        return dedicatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.dedicated_user
     *
     * @param dedicatedUser the value for member_tr_agent_ext.dedicated_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setDedicatedUser(String dedicatedUser) {
        this.dedicatedUser = dedicatedUser == null ? null : dedicatedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_agent_ext.extention
     *
     * @return the value of member_tr_agent_ext.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getExtention() {
        return extention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_agent_ext.extention
     *
     * @param extention the value for member_tr_agent_ext.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setExtention(String extention) {
        this.extention = extention == null ? null : extention.trim();
    }
}