package com.vhouzi.abc.admin.agent.domain;

import java.util.Date;

public class AgentAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.balance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.availableBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String availablebalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.frozenBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String frozenbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.withdrawBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String withdrawbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.currencyCode
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String currencycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_member_account.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String extention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.id
     *
     * @return the value of member_tr_member_account.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.id
     *
     * @param id the value for member_tr_member_account.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.member_id
     *
     * @return the value of member_tr_member_account.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.member_id
     *
     * @param memberId the value for member_tr_member_account.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.balance
     *
     * @return the value of member_tr_member_account.balance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.balance
     *
     * @param balance the value for member_tr_member_account.balance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.availableBalance
     *
     * @return the value of member_tr_member_account.availableBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getAvailablebalance() {
        return availablebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.availableBalance
     *
     * @param availablebalance the value for member_tr_member_account.availableBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setAvailablebalance(String availablebalance) {
        this.availablebalance = availablebalance == null ? null : availablebalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.frozenBalance
     *
     * @return the value of member_tr_member_account.frozenBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getFrozenbalance() {
        return frozenbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.frozenBalance
     *
     * @param frozenbalance the value for member_tr_member_account.frozenBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setFrozenbalance(String frozenbalance) {
        this.frozenbalance = frozenbalance == null ? null : frozenbalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.withdrawBalance
     *
     * @return the value of member_tr_member_account.withdrawBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getWithdrawbalance() {
        return withdrawbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.withdrawBalance
     *
     * @param withdrawbalance the value for member_tr_member_account.withdrawBalance
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setWithdrawbalance(String withdrawbalance) {
        this.withdrawbalance = withdrawbalance == null ? null : withdrawbalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.currencyCode
     *
     * @return the value of member_tr_member_account.currencyCode
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCurrencycode() {
        return currencycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.currencyCode
     *
     * @param currencycode the value for member_tr_member_account.currencyCode
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode == null ? null : currencycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.status
     *
     * @return the value of member_tr_member_account.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.status
     *
     * @param status the value for member_tr_member_account.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.create_time
     *
     * @return the value of member_tr_member_account.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.create_time
     *
     * @param createTime the value for member_tr_member_account.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.update_time
     *
     * @return the value of member_tr_member_account.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.update_time
     *
     * @param updateTime the value for member_tr_member_account.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.create_user
     *
     * @return the value of member_tr_member_account.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.create_user
     *
     * @param createUser the value for member_tr_member_account.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.update_user
     *
     * @return the value of member_tr_member_account.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.update_user
     *
     * @param updateUser the value for member_tr_member_account.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_member_account.extention
     *
     * @return the value of member_tr_member_account.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getExtention() {
        return extention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_member_account.extention
     *
     * @param extention the value for member_tr_member_account.extention
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setExtention(String extention) {
        this.extention = extention == null ? null : extention.trim();
    }
}