package com.vhouzi.abc.admin.agent.domain;

import java.util.Date;

public class AgentRebate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_order_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberCardOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_order_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String memberCardOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.open_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long openMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_realname
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String memberRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_mobile
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String memberMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String memberCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String memberCardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_expires
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberCardExpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.member_card_order_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String memberCardOrderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.rebate_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String rebateAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.agent_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long agentMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.rebate_status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long rebateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_rebate.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.id
     *
     * @return the value of agent_th_rebate.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.id
     *
     * @param id the value for agent_th_rebate.id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_order_id
     *
     * @return the value of agent_th_rebate.member_card_order_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberCardOrderId() {
        return memberCardOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_order_id
     *
     * @param memberCardOrderId the value for agent_th_rebate.member_card_order_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardOrderId(Long memberCardOrderId) {
        this.memberCardOrderId = memberCardOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_order_no
     *
     * @return the value of agent_th_rebate.member_card_order_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getMemberCardOrderNo() {
        return memberCardOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_order_no
     *
     * @param memberCardOrderNo the value for agent_th_rebate.member_card_order_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardOrderNo(String memberCardOrderNo) {
        this.memberCardOrderNo = memberCardOrderNo == null ? null : memberCardOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_id
     *
     * @return the value of agent_th_rebate.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_id
     *
     * @param memberId the value for agent_th_rebate.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.open_member_id
     *
     * @return the value of agent_th_rebate.open_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getOpenMemberId() {
        return openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.open_member_id
     *
     * @param openMemberId the value for agent_th_rebate.open_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setOpenMemberId(Long openMemberId) {
        this.openMemberId = openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_realname
     *
     * @return the value of agent_th_rebate.member_realname
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getMemberRealname() {
        return memberRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_realname
     *
     * @param memberRealname the value for agent_th_rebate.member_realname
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberRealname(String memberRealname) {
        this.memberRealname = memberRealname == null ? null : memberRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_mobile
     *
     * @return the value of agent_th_rebate.member_mobile
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getMemberMobile() {
        return memberMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_mobile
     *
     * @param memberMobile the value for agent_th_rebate.member_mobile
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberMobile(String memberMobile) {
        this.memberMobile = memberMobile == null ? null : memberMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_id
     *
     * @return the value of agent_th_rebate.member_card_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberCardId() {
        return memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_id
     *
     * @param memberCardId the value for agent_th_rebate.member_card_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardId(Long memberCardId) {
        this.memberCardId = memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_no
     *
     * @return the value of agent_th_rebate.member_card_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getMemberCardNo() {
        return memberCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_no
     *
     * @param memberCardNo the value for agent_th_rebate.member_card_no
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardNo(String memberCardNo) {
        this.memberCardNo = memberCardNo == null ? null : memberCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_name
     *
     * @return the value of agent_th_rebate.member_card_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getMemberCardName() {
        return memberCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_name
     *
     * @param memberCardName the value for agent_th_rebate.member_card_name
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardName(String memberCardName) {
        this.memberCardName = memberCardName == null ? null : memberCardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_type
     *
     * @return the value of agent_th_rebate.member_card_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberCardType() {
        return memberCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_type
     *
     * @param memberCardType the value for agent_th_rebate.member_card_type
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardType(Long memberCardType) {
        this.memberCardType = memberCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_expires
     *
     * @return the value of agent_th_rebate.member_card_expires
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberCardExpires() {
        return memberCardExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_expires
     *
     * @param memberCardExpires the value for agent_th_rebate.member_card_expires
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardExpires(Long memberCardExpires) {
        this.memberCardExpires = memberCardExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.member_card_order_amount
     *
     * @return the value of agent_th_rebate.member_card_order_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getMemberCardOrderAmount() {
        return memberCardOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.member_card_order_amount
     *
     * @param memberCardOrderAmount the value for agent_th_rebate.member_card_order_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberCardOrderAmount(String memberCardOrderAmount) {
        this.memberCardOrderAmount = memberCardOrderAmount == null ? null : memberCardOrderAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.rebate_amount
     *
     * @return the value of agent_th_rebate.rebate_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getRebateAmount() {
        return rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.rebate_amount
     *
     * @param rebateAmount the value for agent_th_rebate.rebate_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setRebateAmount(String rebateAmount) {
        this.rebateAmount = rebateAmount == null ? null : rebateAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.agent_member_id
     *
     * @return the value of agent_th_rebate.agent_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getAgentMemberId() {
        return agentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.agent_member_id
     *
     * @param agentMemberId the value for agent_th_rebate.agent_member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setAgentMemberId(Long agentMemberId) {
        this.agentMemberId = agentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.rebate_status
     *
     * @return the value of agent_th_rebate.rebate_status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getRebateStatus() {
        return rebateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.rebate_status
     *
     * @param rebateStatus the value for agent_th_rebate.rebate_status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setRebateStatus(Long rebateStatus) {
        this.rebateStatus = rebateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.create_time
     *
     * @return the value of agent_th_rebate.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.create_time
     *
     * @param createTime the value for agent_th_rebate.create_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.update_time
     *
     * @return the value of agent_th_rebate.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.update_time
     *
     * @param updateTime the value for agent_th_rebate.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.create_user
     *
     * @return the value of agent_th_rebate.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.create_user
     *
     * @param createUser the value for agent_th_rebate.create_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_rebate.update_user
     *
     * @return the value of agent_th_rebate.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_rebate.update_user
     *
     * @param updateUser the value for agent_th_rebate.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}