package com.vhouzi.abc.admin.agent.domain;

import java.util.Date;

public class AgentApplyCash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.int
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.apply_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String applyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.apply_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.bank_transfer_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String bankTransferAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.bank_transfer_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date bankTransferTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_th_apply_cash.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.int
     *
     * @return the value of agent_th_apply_cash.int
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.int
     *
     * @param id the value for agent_th_apply_cash.int
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setInt(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.member_id
     *
     * @return the value of agent_th_apply_cash.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.member_id
     *
     * @param memberId the value for agent_th_apply_cash.member_id
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.apply_amount
     *
     * @return the value of agent_th_apply_cash.apply_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getApplyAmount() {
        return applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.apply_amount
     *
     * @param applyAmount the value for agent_th_apply_cash.apply_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setApplyAmount(String applyAmount) {
        this.applyAmount = applyAmount == null ? null : applyAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.apply_time
     *
     * @return the value of agent_th_apply_cash.apply_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.apply_time
     *
     * @param applyTime the value for agent_th_apply_cash.apply_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.bank_transfer_amount
     *
     * @return the value of agent_th_apply_cash.bank_transfer_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getBankTransferAmount() {
        return bankTransferAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.bank_transfer_amount
     *
     * @param bankTransferAmount the value for agent_th_apply_cash.bank_transfer_amount
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBankTransferAmount(String bankTransferAmount) {
        this.bankTransferAmount = bankTransferAmount == null ? null : bankTransferAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.bank_transfer_time
     *
     * @return the value of agent_th_apply_cash.bank_transfer_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getBankTransferTime() {
        return bankTransferTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.bank_transfer_time
     *
     * @param bankTransferTime the value for agent_th_apply_cash.bank_transfer_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setBankTransferTime(Date bankTransferTime) {
        this.bankTransferTime = bankTransferTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.status
     *
     * @return the value of agent_th_apply_cash.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.status
     *
     * @param status the value for agent_th_apply_cash.status
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.update_time
     *
     * @return the value of agent_th_apply_cash.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.update_time
     *
     * @param updateTime the value for agent_th_apply_cash.update_time
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_th_apply_cash.update_user
     *
     * @return the value of agent_th_apply_cash.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_th_apply_cash.update_user
     *
     * @param updateUser the value for agent_th_apply_cash.update_user
     *
     * @mbggenerated Tue Dec 31 13:50:38 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}