package com.vhouzi.abc.admin.stu.domain;

import java.util.Date;

public class StuCreditLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tl_credit.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tl_credit.old_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long oldCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tl_credit.credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tl_credit.new_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long newCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tl_credit.credit_type_desc
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String creditTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tl_credit.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tl_credit.member_id
     *
     * @return the value of student_tl_credit.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tl_credit.member_id
     *
     * @param memberId the value for student_tl_credit.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tl_credit.old_credit
     *
     * @return the value of student_tl_credit.old_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getOldCredit() {
        return oldCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tl_credit.old_credit
     *
     * @param oldCredit the value for student_tl_credit.old_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setOldCredit(Long oldCredit) {
        this.oldCredit = oldCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tl_credit.credit
     *
     * @return the value of student_tl_credit.credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tl_credit.credit
     *
     * @param credit the value for student_tl_credit.credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCredit(Long credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tl_credit.new_credit
     *
     * @return the value of student_tl_credit.new_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getNewCredit() {
        return newCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tl_credit.new_credit
     *
     * @param newCredit the value for student_tl_credit.new_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setNewCredit(Long newCredit) {
        this.newCredit = newCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tl_credit.credit_type_desc
     *
     * @return the value of student_tl_credit.credit_type_desc
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getCreditTypeDesc() {
        return creditTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tl_credit.credit_type_desc
     *
     * @param creditTypeDesc the value for student_tl_credit.credit_type_desc
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCreditTypeDesc(String creditTypeDesc) {
        this.creditTypeDesc = creditTypeDesc == null ? null : creditTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tl_credit.create_time
     *
     * @return the value of student_tl_credit.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tl_credit.create_time
     *
     * @param createTime the value for student_tl_credit.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}