package com.vhouzi.abc.admin.stu.domain;

import java.util.Date;

public class StudentExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.gender
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.birthday
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.eng_age
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long engAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.province_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.province
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.city_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.city
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.area_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.area
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.address
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.from_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String fromIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.register_source
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long registerSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.register_source_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String registerSourceExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.verify_level
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long verifyLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.create_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_tr_student_ext.update_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.member_id
     *
     * @return the value of member_tr_student_ext.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.member_id
     *
     * @param memberId the value for member_tr_student_ext.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.gender
     *
     * @return the value of member_tr_student_ext.gender
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.gender
     *
     * @param gender the value for member_tr_student_ext.gender
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setGender(Long gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.birthday
     *
     * @return the value of member_tr_student_ext.birthday
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.birthday
     *
     * @param birthday the value for member_tr_student_ext.birthday
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.grade
     *
     * @return the value of member_tr_student_ext.grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.grade
     *
     * @param grade the value for member_tr_student_ext.grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setGrade(Long grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.eng_age
     *
     * @return the value of member_tr_student_ext.eng_age
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getEngAge() {
        return engAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.eng_age
     *
     * @param engAge the value for member_tr_student_ext.eng_age
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setEngAge(Long engAge) {
        this.engAge = engAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.province_code
     *
     * @return the value of member_tr_student_ext.province_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.province_code
     *
     * @param provinceCode the value for member_tr_student_ext.province_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.province
     *
     * @return the value of member_tr_student_ext.province
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.province
     *
     * @param province the value for member_tr_student_ext.province
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.city_code
     *
     * @return the value of member_tr_student_ext.city_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.city_code
     *
     * @param cityCode the value for member_tr_student_ext.city_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.city
     *
     * @return the value of member_tr_student_ext.city
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.city
     *
     * @param city the value for member_tr_student_ext.city
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.area_code
     *
     * @return the value of member_tr_student_ext.area_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.area_code
     *
     * @param areaCode the value for member_tr_student_ext.area_code
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.area
     *
     * @return the value of member_tr_student_ext.area
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.area
     *
     * @param area the value for member_tr_student_ext.area
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.address
     *
     * @return the value of member_tr_student_ext.address
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.address
     *
     * @param address the value for member_tr_student_ext.address
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.from_ip
     *
     * @return the value of member_tr_student_ext.from_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.from_ip
     *
     * @param fromIp the value for member_tr_student_ext.from_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp == null ? null : fromIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.register_source
     *
     * @return the value of member_tr_student_ext.register_source
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getRegisterSource() {
        return registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.register_source
     *
     * @param registerSource the value for member_tr_student_ext.register_source
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setRegisterSource(Long registerSource) {
        this.registerSource = registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.register_source_ext
     *
     * @return the value of member_tr_student_ext.register_source_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getRegisterSourceExt() {
        return registerSourceExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.register_source_ext
     *
     * @param registerSourceExt the value for member_tr_student_ext.register_source_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setRegisterSourceExt(String registerSourceExt) {
        this.registerSourceExt = registerSourceExt == null ? null : registerSourceExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.verify_level
     *
     * @return the value of member_tr_student_ext.verify_level
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getVerifyLevel() {
        return verifyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.verify_level
     *
     * @param verifyLevel the value for member_tr_student_ext.verify_level
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setVerifyLevel(Long verifyLevel) {
        this.verifyLevel = verifyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.create_time
     *
     * @return the value of member_tr_student_ext.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.create_time
     *
     * @param createTime the value for member_tr_student_ext.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.update_time
     *
     * @return the value of member_tr_student_ext.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.update_time
     *
     * @param updateTime the value for member_tr_student_ext.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.create_user
     *
     * @return the value of member_tr_student_ext.create_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.create_user
     *
     * @param createUser the value for member_tr_student_ext.create_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_tr_student_ext.update_user
     *
     * @return the value of member_tr_student_ext.update_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_tr_student_ext.update_user
     *
     * @param updateUser the value for member_tr_student_ext.update_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}