package com.vhouzi.abc.admin.stu.domain;

import java.util.Date;

public class StuLCHisto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long studentMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.course_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.first_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date firstTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.last_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.first_heartbeat_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date firstHeartbeatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.last_heartbeat_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date lastHeartbeatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.actual_listen_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long actualListenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.watch_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String watchIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.province
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.city
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.network_operator
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String networkOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.is_audition
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long isAudition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_live_study.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.id
     *
     * @return the value of student_th_live_study.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.id
     *
     * @param id the value for student_th_live_study.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.student_member_id
     *
     * @return the value of student_th_live_study.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getStudentMemberId() {
        return studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.student_member_id
     *
     * @param studentMemberId the value for student_th_live_study.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setStudentMemberId(Long studentMemberId) {
        this.studentMemberId = studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.course_id
     *
     * @return the value of student_th_live_study.course_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.course_id
     *
     * @param courseId the value for student_th_live_study.course_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.first_time
     *
     * @return the value of student_th_live_study.first_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getFirstTime() {
        return firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.first_time
     *
     * @param firstTime the value for student_th_live_study.first_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.last_time
     *
     * @return the value of student_th_live_study.last_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.last_time
     *
     * @param lastTime the value for student_th_live_study.last_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.first_heartbeat_time
     *
     * @return the value of student_th_live_study.first_heartbeat_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getFirstHeartbeatTime() {
        return firstHeartbeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.first_heartbeat_time
     *
     * @param firstHeartbeatTime the value for student_th_live_study.first_heartbeat_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setFirstHeartbeatTime(Date firstHeartbeatTime) {
        this.firstHeartbeatTime = firstHeartbeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.last_heartbeat_time
     *
     * @return the value of student_th_live_study.last_heartbeat_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getLastHeartbeatTime() {
        return lastHeartbeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.last_heartbeat_time
     *
     * @param lastHeartbeatTime the value for student_th_live_study.last_heartbeat_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setLastHeartbeatTime(Date lastHeartbeatTime) {
        this.lastHeartbeatTime = lastHeartbeatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.actual_listen_time
     *
     * @return the value of student_th_live_study.actual_listen_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getActualListenTime() {
        return actualListenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.actual_listen_time
     *
     * @param actualListenTime the value for student_th_live_study.actual_listen_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setActualListenTime(Long actualListenTime) {
        this.actualListenTime = actualListenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.watch_ip
     *
     * @return the value of student_th_live_study.watch_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getWatchIp() {
        return watchIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.watch_ip
     *
     * @param watchIp the value for student_th_live_study.watch_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setWatchIp(String watchIp) {
        this.watchIp = watchIp == null ? null : watchIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.province
     *
     * @return the value of student_th_live_study.province
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.province
     *
     * @param province the value for student_th_live_study.province
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.city
     *
     * @return the value of student_th_live_study.city
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.city
     *
     * @param city the value for student_th_live_study.city
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.network_operator
     *
     * @return the value of student_th_live_study.network_operator
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getNetworkOperator() {
        return networkOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.network_operator
     *
     * @param networkOperator the value for student_th_live_study.network_operator
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setNetworkOperator(String networkOperator) {
        this.networkOperator = networkOperator == null ? null : networkOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.client_type
     *
     * @return the value of student_th_live_study.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.client_type
     *
     * @param clientType the value for student_th_live_study.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setClientType(Long clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.is_audition
     *
     * @return the value of student_th_live_study.is_audition
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getIsAudition() {
        return isAudition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.is_audition
     *
     * @param isAudition the value for student_th_live_study.is_audition
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setIsAudition(Long isAudition) {
        this.isAudition = isAudition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.create_time
     *
     * @return the value of student_th_live_study.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.create_time
     *
     * @param createTime the value for student_th_live_study.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_live_study.update_time
     *
     * @return the value of student_th_live_study.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_live_study.update_time
     *
     * @param updateTime the value for student_th_live_study.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}