package com.vhouzi.abc.admin.stu.domain;

public class StuRCHisto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long studentMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.course_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.guid
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.play_begin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String playBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.play_end_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String playEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.play_length
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long playLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.watch_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String watchIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_video_study.area
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String area;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.id
     *
     * @return the value of student_th_video_study.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.id
     *
     * @param id the value for student_th_video_study.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.student_member_id
     *
     * @return the value of student_th_video_study.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getStudentMemberId() {
        return studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.student_member_id
     *
     * @param studentMemberId the value for student_th_video_study.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setStudentMemberId(Long studentMemberId) {
        this.studentMemberId = studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.course_id
     *
     * @return the value of student_th_video_study.course_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.course_id
     *
     * @param courseId the value for student_th_video_study.course_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.guid
     *
     * @return the value of student_th_video_study.guid
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.guid
     *
     * @param guid the value for student_th_video_study.guid
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.play_begin_time
     *
     * @return the value of student_th_video_study.play_begin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getPlayBeginTime() {
        return playBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.play_begin_time
     *
     * @param playBeginTime the value for student_th_video_study.play_begin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setPlayBeginTime(String playBeginTime) {
        this.playBeginTime = playBeginTime == null ? null : playBeginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.play_end_time
     *
     * @return the value of student_th_video_study.play_end_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getPlayEndTime() {
        return playEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.play_end_time
     *
     * @param playEndTime the value for student_th_video_study.play_end_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setPlayEndTime(String playEndTime) {
        this.playEndTime = playEndTime == null ? null : playEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.play_length
     *
     * @return the value of student_th_video_study.play_length
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getPlayLength() {
        return playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.play_length
     *
     * @param playLength the value for student_th_video_study.play_length
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setPlayLength(Long playLength) {
        this.playLength = playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.client_type
     *
     * @return the value of student_th_video_study.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.client_type
     *
     * @param clientType the value for student_th_video_study.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setClientType(Long clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.watch_ip
     *
     * @return the value of student_th_video_study.watch_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getWatchIp() {
        return watchIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.watch_ip
     *
     * @param watchIp the value for student_th_video_study.watch_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setWatchIp(String watchIp) {
        this.watchIp = watchIp == null ? null : watchIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_video_study.area
     *
     * @return the value of student_th_video_study.area
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_video_study.area
     *
     * @param area the value for student_th_video_study.area
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }
}