package com.vhouzi.abc.admin.stu.domain;

import java.util.Date;

public class StuSigninHisto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.id
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.student_member_id
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private Long studentMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.signin_time
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private Date signinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.from_ip
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private String fromIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.client_type
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private Integer clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.token
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.state
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.app_version
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    private String appVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.id
     *
     * @return the value of student_th_signin.id
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.id
     *
     * @param id the value for student_th_signin.id
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.student_member_id
     *
     * @return the value of student_th_signin.student_member_id
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public Long getStudentMemberId() {
        return studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.student_member_id
     *
     * @param studentMemberId the value for student_th_signin.student_member_id
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setStudentMemberId(Long studentMemberId) {
        this.studentMemberId = studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.signin_time
     *
     * @return the value of student_th_signin.signin_time
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public Date getSigninTime() {
        return signinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.signin_time
     *
     * @param signinTime the value for student_th_signin.signin_time
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setSigninTime(Date signinTime) {
        this.signinTime = signinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.from_ip
     *
     * @return the value of student_th_signin.from_ip
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.from_ip
     *
     * @param fromIp the value for student_th_signin.from_ip
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp == null ? null : fromIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.client_type
     *
     * @return the value of student_th_signin.client_type
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.client_type
     *
     * @param clientType the value for student_th_signin.client_type
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.token
     *
     * @return the value of student_th_signin.token
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.token
     *
     * @param token the value for student_th_signin.token
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.state
     *
     * @return the value of student_th_signin.state
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.state
     *
     * @param state the value for student_th_signin.state
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.app_version
     *
     * @return the value of student_th_signin.app_version
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.app_version
     *
     * @param appVersion the value for student_th_signin.app_version
     *
     * @mbggenerated Thu Mar 26 10:24:05 CST 2020
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }
}