package com.vhouzi.abc.admin.stu.domain;

import java.util.Date;

public class StuSigninHisto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long studentMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.signin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date signinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.from_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String fromIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_th_signin.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long clientType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.id
     *
     * @return the value of student_th_signin.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.id
     *
     * @param id the value for student_th_signin.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.student_member_id
     *
     * @return the value of student_th_signin.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getStudentMemberId() {
        return studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.student_member_id
     *
     * @param studentMemberId the value for student_th_signin.student_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setStudentMemberId(Long studentMemberId) {
        this.studentMemberId = studentMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.signin_time
     *
     * @return the value of student_th_signin.signin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getSigninTime() {
        return signinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.signin_time
     *
     * @param signinTime the value for student_th_signin.signin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setSigninTime(Date signinTime) {
        this.signinTime = signinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.from_ip
     *
     * @return the value of student_th_signin.from_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.from_ip
     *
     * @param fromIp the value for student_th_signin.from_ip
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp == null ? null : fromIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_th_signin.client_type
     *
     * @return the value of student_th_signin.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_th_signin.client_type
     *
     * @param clientType the value for student_th_signin.client_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setClientType(Long clientType) {
        this.clientType = clientType;
    }
}