package com.vhouzi.abc.admin.stu.domain;

import java.util.Date;

public class StuVipCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.open_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long openMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_card_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long memberCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_card_no
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String memberCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_card_name
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String memberCardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_card_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long memberCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_card_expires
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Long memberCardExpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_card_begin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date memberCardBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.member_card_end_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date memberCardEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.create_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_tr_member_card.update_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.id
     *
     * @return the value of student_tr_member_card.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.id
     *
     * @param id the value for student_tr_member_card.id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_id
     *
     * @return the value of student_tr_member_card.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_id
     *
     * @param memberId the value for student_tr_member_card.member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.open_member_id
     *
     * @return the value of student_tr_member_card.open_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getOpenMemberId() {
        return openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.open_member_id
     *
     * @param openMemberId the value for student_tr_member_card.open_member_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setOpenMemberId(Long openMemberId) {
        this.openMemberId = openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_card_id
     *
     * @return the value of student_tr_member_card.member_card_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getMemberCardId() {
        return memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_card_id
     *
     * @param memberCardId the value for student_tr_member_card.member_card_id
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberCardId(Long memberCardId) {
        this.memberCardId = memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_card_no
     *
     * @return the value of student_tr_member_card.member_card_no
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getMemberCardNo() {
        return memberCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_card_no
     *
     * @param memberCardNo the value for student_tr_member_card.member_card_no
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberCardNo(String memberCardNo) {
        this.memberCardNo = memberCardNo == null ? null : memberCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_card_name
     *
     * @return the value of student_tr_member_card.member_card_name
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getMemberCardName() {
        return memberCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_card_name
     *
     * @param memberCardName the value for student_tr_member_card.member_card_name
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberCardName(String memberCardName) {
        this.memberCardName = memberCardName == null ? null : memberCardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_card_type
     *
     * @return the value of student_tr_member_card.member_card_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getMemberCardType() {
        return memberCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_card_type
     *
     * @param memberCardType the value for student_tr_member_card.member_card_type
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberCardType(Long memberCardType) {
        this.memberCardType = memberCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_card_expires
     *
     * @return the value of student_tr_member_card.member_card_expires
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Long getMemberCardExpires() {
        return memberCardExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_card_expires
     *
     * @param memberCardExpires the value for student_tr_member_card.member_card_expires
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberCardExpires(Long memberCardExpires) {
        this.memberCardExpires = memberCardExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_card_begin_time
     *
     * @return the value of student_tr_member_card.member_card_begin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getMemberCardBeginTime() {
        return memberCardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_card_begin_time
     *
     * @param memberCardBeginTime the value for student_tr_member_card.member_card_begin_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberCardBeginTime(Date memberCardBeginTime) {
        this.memberCardBeginTime = memberCardBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.member_card_end_time
     *
     * @return the value of student_tr_member_card.member_card_end_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getMemberCardEndTime() {
        return memberCardEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.member_card_end_time
     *
     * @param memberCardEndTime the value for student_tr_member_card.member_card_end_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setMemberCardEndTime(Date memberCardEndTime) {
        this.memberCardEndTime = memberCardEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.create_time
     *
     * @return the value of student_tr_member_card.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.create_time
     *
     * @param createTime the value for student_tr_member_card.create_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.update_time
     *
     * @return the value of student_tr_member_card.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.update_time
     *
     * @param updateTime the value for student_tr_member_card.update_time
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.create_user
     *
     * @return the value of student_tr_member_card.create_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.create_user
     *
     * @param createUser the value for student_tr_member_card.create_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_tr_member_card.update_user
     *
     * @return the value of student_tr_member_card.update_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_tr_member_card.update_user
     *
     * @param updateUser the value for student_tr_member_card.update_user
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}