package com.vhouzi.abc.admin.notification.mapper;

import com.vhouzi.abc.admin.notification.domain.Push;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_push
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_push
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    int insert(Push record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_push
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    Push selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_push
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    List<Push> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_push
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    int updateByPrimaryKey(Push record);
}