package com.vhouzi.abc.admin.notification.mapper;

import com.vhouzi.abc.admin.notification.domain.PushTpl;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PushTplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_push_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_push_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    int insert(PushTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_push_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    PushTpl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_push_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    List<PushTpl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_push_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    int updateByPrimaryKey(PushTpl record);
}