package com.vhouzi.abc.admin.notification.mapper;

import com.vhouzi.abc.admin.notification.domain.Sms;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface SmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_sms
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_sms
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    int insert(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_sms
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    Sms selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_sms
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    List<Sms> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_th_sms
     *
     * @mbggenerated Fri Jan 03 14:32:55 CST 2020
     */
    int updateByPrimaryKey(Sms record);

    int countDayTime(Map<String, Object> data);

    int countTimes(Map countInSomeTimeMap);
}