package com.vhouzi.abc.admin.notification.mapper;

import com.vhouzi.abc.admin.notification.domain.SmsTpl;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface SmsTplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_sms_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_sms_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    int insert(SmsTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_sms_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    SmsTpl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_sms_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    List<SmsTpl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_tm_sms_tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    int updateByPrimaryKey(SmsTpl record);

    SmsTpl findSelective(Map<String, Object> params);

    int deleteSysSmsTemplateByIds(String[] ids);

    List<SmsTpl> listByObj(SmsTpl sysSmsTemplate);
}