package com.vhouzi.abc.admin.stu.mapper;

import com.vhouzi.abc.admin.stu.domain.StuCreditLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StuCreditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tl_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tl_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int insert(StuCreditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tl_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    StuCreditLog selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tl_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    List<StuCreditLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tl_credit
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int updateByPrimaryKey(StuCreditLog record);
}