package com.vhouzi.abc.admin.stu.mapper;

import com.vhouzi.abc.admin.stu.domain.StudentExt;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StudentExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_student_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_student_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int insert(StudentExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_student_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    StudentExt selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_student_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    List<StudentExt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tr_student_ext
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int updateByPrimaryKey(StudentExt record);
}