package com.vhouzi.abc.admin.stu.mapper;

import com.vhouzi.abc.admin.stu.domain.Student;
import com.vhouzi.abc.admin.stu.dto.StudentDTO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_student
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int deleteByPrimaryKey(Long openMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_student
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_student
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    Student selectByPrimaryKey(Long openMemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_student
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tm_student
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int updateByPrimaryKey(Student record);

    StudentDTO findSelective(Map<String, Object> params);
}