package com.vhouzi.abc.admin.stu.mapper;

import com.vhouzi.abc.admin.stu.domain.StuGradeHisto;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StuGradeHistoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int insert(StuGradeHisto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    StuGradeHisto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    List<StuGradeHisto> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_grade
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int updateByPrimaryKey(StuGradeHisto record);
}