package com.vhouzi.abc.admin.stu.mapper;

import com.vhouzi.abc.admin.stu.domain.StuLCHisto;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StuLCHistoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_live_study
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_live_study
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int insert(StuLCHisto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_live_study
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    StuLCHisto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_live_study
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    List<StuLCHisto> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_live_study
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int updateByPrimaryKey(StuLCHisto record);
}