package com.vhouzi.abc.admin.stu.mapper;

import com.vhouzi.abc.admin.stu.domain.StuSigninHisto;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StuSigninHistoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_signin
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_signin
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int insert(StuSigninHisto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_signin
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    StuSigninHisto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_signin
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    List<StuSigninHisto> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_th_signin
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int updateByPrimaryKey(StuSigninHisto record);
}