package com.vhouzi.abc.admin.stu.mapper;

import com.vhouzi.abc.admin.stu.domain.StuVipCard;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StuVipCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tr_member_card
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tr_member_card
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int insert(StuVipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tr_member_card
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    StuVipCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tr_member_card
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    List<StuVipCard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_tr_member_card
     *
     * @mbggenerated Thu Jan 02 17:51:19 CST 2020
     */
    int updateByPrimaryKey(StuVipCard record);
}