package com.vhouzi.abc.admin.notification.domain;

import java.util.Date;

public class PushTpl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_tm_push_tpl.id
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_tm_push_tpl.type
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_tm_push_tpl.type_name
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_tm_push_tpl.tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    private String tpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_tm_push_tpl.create_time
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_tm_push_tpl.update_time
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_tm_push_tpl.status
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    private Long status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_tm_push_tpl.id
     *
     * @return the value of notify_tm_push_tpl.id
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_tm_push_tpl.id
     *
     * @param id the value for notify_tm_push_tpl.id
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_tm_push_tpl.type
     *
     * @return the value of notify_tm_push_tpl.type
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_tm_push_tpl.type
     *
     * @param type the value for notify_tm_push_tpl.type
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_tm_push_tpl.type_name
     *
     * @return the value of notify_tm_push_tpl.type_name
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_tm_push_tpl.type_name
     *
     * @param typeName the value for notify_tm_push_tpl.type_name
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_tm_push_tpl.tpl
     *
     * @return the value of notify_tm_push_tpl.tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public String getTpl() {
        return tpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_tm_push_tpl.tpl
     *
     * @param tpl the value for notify_tm_push_tpl.tpl
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public void setTpl(String tpl) {
        this.tpl = tpl == null ? null : tpl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_tm_push_tpl.create_time
     *
     * @return the value of notify_tm_push_tpl.create_time
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_tm_push_tpl.create_time
     *
     * @param createTime the value for notify_tm_push_tpl.create_time
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_tm_push_tpl.update_time
     *
     * @return the value of notify_tm_push_tpl.update_time
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_tm_push_tpl.update_time
     *
     * @param updateTime the value for notify_tm_push_tpl.update_time
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_tm_push_tpl.status
     *
     * @return the value of notify_tm_push_tpl.status
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_tm_push_tpl.status
     *
     * @param status the value for notify_tm_push_tpl.status
     *
     * @mbggenerated Fri Jan 03 20:14:46 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }
}