package com.vhouzi.abc.admin.notification.domain;

import java.util.Date;

public class Sms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.mobile
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.open_member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Long openMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.content
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.send_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.create_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.status
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_sms.type
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.id
     *
     * @return the value of notify_th_sms.id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.id
     *
     * @param id the value for notify_th_sms.id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.mobile
     *
     * @return the value of notify_th_sms.mobile
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.mobile
     *
     * @param mobile the value for notify_th_sms.mobile
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.open_member_id
     *
     * @return the value of notify_th_sms.open_member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Long getOpenMemberId() {
        return openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.open_member_id
     *
     * @param openMemberId the value for notify_th_sms.open_member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setOpenMemberId(Long openMemberId) {
        this.openMemberId = openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.member_id
     *
     * @return the value of notify_th_sms.member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.member_id
     *
     * @param memberId the value for notify_th_sms.member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.content
     *
     * @return the value of notify_th_sms.content
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.content
     *
     * @param content the value for notify_th_sms.content
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.send_time
     *
     * @return the value of notify_th_sms.send_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.send_time
     *
     * @param sendTime the value for notify_th_sms.send_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.create_time
     *
     * @return the value of notify_th_sms.create_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.create_time
     *
     * @param createTime the value for notify_th_sms.create_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.status
     *
     * @return the value of notify_th_sms.status
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.status
     *
     * @param status the value for notify_th_sms.status
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_sms.type
     *
     * @return the value of notify_th_sms.type
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_sms.type
     *
     * @param type the value for notify_th_sms.type
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}