package com.vhouzi.abc.admin.notification.domain;

import java.util.Date;

public class WxPush {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.open_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.open_member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Long openMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.content
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.send_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.create_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_th_wx_push.type
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.id
     *
     * @return the value of notify_th_wx_push.id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.id
     *
     * @param id the value for notify_th_wx_push.id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.open_id
     *
     * @return the value of notify_th_wx_push.open_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.open_id
     *
     * @param openId the value for notify_th_wx_push.open_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.open_member_id
     *
     * @return the value of notify_th_wx_push.open_member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Long getOpenMemberId() {
        return openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.open_member_id
     *
     * @param openMemberId the value for notify_th_wx_push.open_member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setOpenMemberId(Long openMemberId) {
        this.openMemberId = openMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.member_id
     *
     * @return the value of notify_th_wx_push.member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.member_id
     *
     * @param memberId the value for notify_th_wx_push.member_id
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.content
     *
     * @return the value of notify_th_wx_push.content
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.content
     *
     * @param content the value for notify_th_wx_push.content
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.send_time
     *
     * @return the value of notify_th_wx_push.send_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.send_time
     *
     * @param sendTime the value for notify_th_wx_push.send_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.create_time
     *
     * @return the value of notify_th_wx_push.create_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.create_time
     *
     * @param createTime the value for notify_th_wx_push.create_time
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_th_wx_push.type
     *
     * @return the value of notify_th_wx_push.type
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_th_wx_push.type
     *
     * @param type the value for notify_th_wx_push.type
     *
     * @mbggenerated Fri Jan 03 16:55:34 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}