version: "3.7"
services:
  admin-server:
    image: harbor.5houzi.com/oneabc/admin-server:${BUILD_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.admin-server.rule=Host(`bms.5houzi.com`)"
        - "traefik.http.routers.admin-server.entrypoints=web"
        - "traefik.http.services.admin-server.loadbalancer.server.port=8080"
#        - "traefik.tcp.routers.admin-server.rule=HostSNI(`*`)"#测试配置
#        - "traefik.tcp.routers.admin-server.entrypoints=admin-server"#测试配置
#        - "traefik.tcp.services.admin-server.loadbalancer.server.port=28715"#测试配置
    environment:
      DUBBO_IP_TO_REGISTRY: 101.133.136.18 #测试配置
      DUBBO_PORT_TO_REGISTRY: 28715 #测试配置
      DUBBO_PORT_TO_BIND: 28715
    labels:
      - "aliyun.logs.admin-server-log=stdout"
      #- "aliyun.logs.admin-server-nacos-log=/root/logs/nacos/*.log"
    networks:
      - oneabc-net
#      - nacos-net
#      - proxy-net


networks:
  oneabc-net:
    external: true
#  nacos-net:
#    external: true
#  proxy-net:
#    external: true